version: '3.6'

volumes:
  .ssl-data:

services:

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  # make sure to ng build first (does not work with ng serve)
  # TODO: Get integration to work
  angularui:
    image: nginx:1.20.1-alpine
    container_name: angularui
    volumes:
      - ./AngularUI/dist/AngularUI:/usr/share/nginx/html
      - ./AngularUI/.nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:80
    
  # proxy for ssl certificates, to be tested on prod server
  reverse-proxy:
    image: valian/docker-nginx-auto-ssl:1.2.0
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/resty-auto-ssl
    environment:
      allowed_domains: '(app|admin).example.io' # to be edited
      sites: 'app.example.io=angularui:80' # to be edited
      force_https: "true"
    depends_on:
      - angularui
