version: '3.6'

services:

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  clientapp-dev:
    image: nginx:1.20.1-alpine
    container_name: clientapp-dev
    volumes:
      - ./ClientApp/dist/ClientApp:/usr/share/nginx/html
    ports:
      - 5000:80
  
#  # this container will only contain built files
#  clientapp-prod:
#    image: ${DOCKER_REGISTRY-}clientapp
#    build:
#      context: .
#      dockerfile: ClientApp/.docker/Dockerfile # fails in other location
#    container_name: clientapp-prod
#    volumes:
#      - ./ClientApp/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 5001:80
  
#  # proxy for ssl certificates
#  reverse-proxy:
#    image: valian/docker-nginx-auto-ssl:1.2.0
#    container_name: reverse-proxy
#    restart: on-failure
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./.ssl-data:/etc/resty-auto-ssl
#    environment:
#      ALLOWED_DOMAINS: '(app|admin).example.io' # to be edited
#      SITES: 'app.example.io=clientapp-prod:80' # to be edited
#      FORCE_HTTPS: "true"
#    depends_on:
#      - clientapp-prod

#volumes:
#  .ssl-data:
